baseURL = "https://resume.mithril.be/"
languageCode = "en-us"
title = "Dominic Collart resume"
theme = "devresume"



[params]
    author = "Dominic Collart"
    description = "Dominic Collart resume"


    [params.profile]
        enable = true
        name = "Dominic Collart"
        tagline = "Software/Solution architect specialized in microservices, .NET and web"

    [params.contact]
        enable = true
        location = "Beauvechain, Belgium"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0494/88.87.14"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "dcollart@mithril.be"      

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = ".NET Core (C#)"
        [[params.skills.list.items]]
        details = "ASP.NET Core"
        [[params.skills.list.items]]
        details = "Angular 13+"

        [[params.skills.list]]
        title = "Concepts"
        [[params.skills.list.items]]
        details = "Microservices"
        [[params.skills.list.items]]
        details = "RESTful / HATEOAS"
        [[params.skills.list.items]]
        details = "Software architecture"
        [[params.skills.list.items]]
        details = "DDD"
        [[params.skills.list.items]]
        details = "CQRS"
        [[params.skills.list.items]]
        details = "Event sourcing"
        [[params.skills.list.items]]
        details = "Distributed architecture"
        [[params.skills.list.items]]
        details = "CI/CD"

        [[params.skills.list]]
        title = "Modelling"
        [[params.skills.list.items]]
        details = "UML"
        [[params.skills.list.items]]
        details = "Archimate"

        
        [[params.skills.list]]
        title = "Testing"
        [[params.skills.list.items]]
        details = "TDD/BDD"
        [[params.skills.list.items]]
        details = "XUnit/MsTests/NUnit"
        [[params.skills.list.items]]
        details = "Unit/Integration/End2end tests"
        [[params.skills.list.items]]
        details = "Specflow"
        [[params.skills.list.items]]
        details = "Load tests (JMeter)"

        [[params.skills.list]]
        title = "Soft skills"
        [[params.skills.list.items]]
        details = "Autonomous"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Coaching"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Information technology"
        university = "EPHEC"
        dates = "2010 - 2014"


    [params.awards]
        enable = true
        [[params.awards.list]]
        name = "Azure administrator (AZ-104)"
        body = "Microsoft"
        date = "2023"

        [[params.awards.list]]
        name = "Professionnal Scrum Master I"
        body = "Scrum.org"
        date = "2019"

        [[params.awards.list]]
        name = "Programming in C#"
        body = "Microsoft"
        date = "2014"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Intermediate"

    [params.summary]
        enable = true
        text = "Software/Solution architect with a solution oriented spirit finding the best balance between business needs providing evolutive and stable architecture."

    [params.experience]
        enable = true


        [[params.experience.list]]
        title = "Revamp and maintenance of MyVoo + Performance investigation (Voo)"
        dates = "06/2022 - 01/2024"
        company = "Lead dev - Software architect"
        details = "MyVoo is the B2C platform and the main communication channel to the customer. During this we also integrate with some third party like Airship for web notifications. In parallel some performance issues have been detected and we had to analyze the root cause of it."

            [[params.experience.list.items]]
                details = "Archimate"
            [[params.experience.list.items]]
                details = "Angular 13+"
            [[params.experience.list.items]]
                details = "PWA / Service worker"
            [[params.experience.list.items]]
                details = "ASP.NET Core"
            [[params.experience.list.items]]
                details = "Redis (sentinel)"
            [[params.experience.list.items]]
                details = "Mongo"
            [[params.experience.list.items]]
                details = "Firebase"
            [[params.experience.list.items]]
                details = "Jenkins"
            [[params.experience.list.items]]
                details = "Push notification (Airship)"
            

        [[params.experience.list]]
        title = "ProSalary (Partena)"
        dates = "04/2020 - 06/2022"
        company = "Software architect"
        details = "ProSalary is the new tool developped by Partena in order to propose to SMEs (for the moment) a new experience to manage the employees and the payroll information (contract data, fiscal informations, wage package, package, and more). My focus was as well on the functional requirements than the cross-functional requirements (security, performances, design, documentation, ...) and to make the team evolve in the way of thinking the problem."

            [[params.experience.list.items]]
                details = "ASP.NET Core"
            [[params.experience.list.items]]
                details = "Angular 10+"
            [[params.experience.list.items]]
                details = "Service Fabric"
            [[params.experience.list.items]]
                details = "NServiceBus"
            [[params.experience.list.items]]
                details = "Microservices/SOA"                     
            [[params.experience.list.items]]
                details = "JMeter"
            [[params.experience.list.items]]
                details = "Archimate"
            [[params.experience.list.items]]
                details = "Event storming"
            [[params.experience.list.items]]
                details = "Azure (WAF, AppInsight, APIM)"    

        [[params.experience.list]]
        title = "Audit (Interparking)"
        dates = "01/2019 - 03/2020"
        company = "Solution architect"
        details = "To get compliant for an external audit, we had to analyze the whole end to end cash flow and provide for each step a full report to guarantee our control on these."
            [[params.experience.list.items]]
                details = "Archimate"
            [[params.experience.list.items]]
                details = "SQL"
            [[params.experience.list.items]]
                details = "Data consolidation"

        [[params.experience.list]]
        title = "Invoice per mail (Interparking)"
        dates = "09/2019 - 12/2019"
        company = "Solution architect"
        details = "In order to be able to deliver invoices per mail, some new components had to be developped and some integration with the old system had to be made. "
            [[params.experience.list.items]]
                details = "Archimate"
            [[params.experience.list.items]]
                details = ".NET Core"

        [[params.experience.list]]
        title = "Transaction API (Interparking)"
        dates = "03/2019 - 08/2019"
        company = "Solution architect"
        details = "Some major accounts wanted an automated way to retrieve their multi-products/countries/contracts transactions. A new API has been designed to meet their requirements."
            [[params.experience.list.items]]
                details = "ASP.NET Web API"
            [[params.experience.list.items]]
                details = "ASP.NET Core (PoC not in production)"
            [[params.experience.list.items]]
                details = "Archimate"
            [[params.experience.list.items]]
                details = "Selfhost end2end testing"
            [[params.experience.list.items]]
                details = "Dapper"
            [[params.experience.list.items]]
                details = "Entity framework"

        [[params.experience.list]]
        title = "Subscription2 -Interparking"
        dates = "09/2017 - 12/2018"
        company = "Full stack developer/Scrum master"
        details = "Subscription is the most basic product offered by Interparking. The goal was to be able to bring a technical solution for other countries in the group. The legacy system was not maintainable and extensible enough so the decision was to build a new solution from scratch (contract management, product management, web integration, invoicing, ...)."
            [[params.experience.list.items]]
                details = "ASP.NET Web API"
            [[params.experience.list.items]]
                details = "Onion architecture"
            [[params.experience.list.items]]
                details = "Selfhost end2end testing"
            [[params.experience.list.items]]
                details = "Fluent validation"
            [[params.experience.list.items]]
                details = "Entity framework"

        [[params.experience.list]]
        title = "Servipark API - Interparking"
        dates = "10/2016 - 09/2017"
        company = "Full stack developer"
        details = "Servipark is a company (owned by Interparking) that provides the PCard product (a post paid product that allows customer to access all car parks). The old websites wwere available for multiple countries but were only managed in Belgium. The maintenance cost became higher and the SLA for change request was not good enough for countries. The goal of this project was to provide an restful API in order to let every country in charge of developing their own website."
            [[params.experience.list.items]]
                details = "ASP.NET Web API"
            [[params.experience.list.items]]
                details = "Fluent validation"
            [[params.experience.list.items]]
                details = "Entity framework"
            [[params.experience.list.items]]
                details = "OAuth 2 (Identity server)"
            [[params.experience.list.items]]
                details = "Postman for automated testing"

        [[params.experience.list]]
        title = "Matador adserver - Radionomy"
        dates = "02/2016 - 10/2016"
        company = "Full stack developer"
        details = "Radionomy relies on advertisements for financing and owns a company specialized in audio advertising named Targetspot. The goal of this project was to create an adserver (an application managing campains/flights) specialized for audio world. It was also built to be sold as an SaaS solution for other companies."
            [[params.experience.list.items]]
                details = "ASP.NET MVC"
            [[params.experience.list.items]]
                details = "ASP.NET Web API"
            [[params.experience.list.items]]
                details = "ADO.NET"
            [[params.experience.list.items]]
                details = "HTML/CSS/JS"

        [[params.experience.list]]
        title = "Tizen application - Radionomy"
        dates = "09/2015 - 02/2016"
        company = "Frontend developer"
        details = "Radionomy is a company providing the ability to create and broadcast web radio station. The purpose of this project was to help Radionomy to be available on Tizen (Samsung TV operating system). The applications could be native or web based and we chose the last one for this development."
            [[params.experience.list.items]]
                details = "AngularJS (1.X)"
            [[params.experience.list.items]]
                details = "ASP.NET Web API"

        [[params.experience.list]]
        title = "Roku application - Radionomy"
        dates = "09/2015 - 02/2016"
        company = "Roku developer"
        details = "Radionomy is a company providing the ability to create and broadcast web radio station. The purpose of this project was to help Radionomy to be available on Roku stick (kind of Chromecast)."
            [[params.experience.list.items]]
                details = "Brightscript (proprietary language)"
            [[params.experience.list.items]]
                details = "ASP.NET Web API"

        [[params.experience.list]]
        title = "Casimire - InterMIRE (CogniTIC)"
        dates = "02/2015 - 09/2015"
        company = "Fullstack developer"
        details = "A MIRE (Mission Inter-RÃ©gional pour l'Emploi) is a NPO focused on helping people to find and keep jobs. They are about ~10 of them in the country and in order to be the most efficient they had to collaborate to exchange relevant informations (job seeker profile or job offer). In order to liaise all 10 MIRE's, a new MIRE solely dedicated to inter-communication was created: InterMIRE. This platform was to help them to share and propagate information."
       
            [[params.experience.list.items]]
            details = "ASP.NET MVC"
            [[params.experience.list.items]]
            details = "Entity framework"
            [[params.experience.list.items]]
            details = "HTML/CSS/JS"
            [[params.experience.list.items]]
            details = "SQL Server"
            [[params.experience.list.items]]
            details = "Customer SPA framework"

        [[params.experience.list]]
        title = "Product catalog - Halliburton (CogniTIC)"
        dates = "02/2014 - 10/2014"
        company = "Fullstack developer"
        details = "Halliburton is a company that designs and provides equipments for oil extraction. This project was built to help them manage their products (industrial drill, ...). First part was about a product management that allowed them to create a product from sub-products (a drill could be decomposed until the screw). The second part was about to select a product respecting the constraint established during the creation (Some parts were optional, some were exclusive, ...). Previously they had to work with dozens of excel files (one per [sub]products)."

            [[params.experience.list.items]]
            details = "ASP.NET MVC"
            [[params.experience.list.items]]
            details = "Entity framework"
            [[params.experience.list.items]]
            details = "SQL Server"
            [[params.experience.list.items]]
            details = "HTML/CSS/JS (jQuery)"

        [[params.experience.list]]
        title = "RTV - Auxipress (CogniTIC)"
        dates = "08/2013 - 03/2019"
        company = "Fullstack developer"
        details = "Auxipress is a company specialized in media analysis. This project was built to facilitate the work of the team dedicated to radio and television shows analysis by providing an unified web application. Previously they had to work with multiples applications (video player, note taker, mail agent, ...) and had to warn manually the customers when they were mentionned."
       
            [[params.experience.list.items]]
            details = "ASP.NET MVC"
            [[params.experience.list.items]]
            details = "Entity framework"
            [[params.experience.list.items]]
            details = "FFMPEG (for on the fly transcoding)"
            [[params.experience.list.items]]
            details = "SQL Server"
            [[params.experience.list.items]]
            details = "HTML/CSS/JS (jQuery)"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/dcollart"
        title = "DCollart"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/dominic-collart-2068abb3/"
        title = "Dominic Collart"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/DominicCollart"
        title = "DominicCollart"
        [[params.social.list]]
        icon = "fab fa-stack-overflow"
        url = "//stackoverflow.com/users/5581561/arcord"
        title = "Arcord"